const features = [
  {
    key: 'children',
    path: '/children',
    title: 'Child Profiles',
    icon: '👶',
    description: 'Manage your children\'s profiles and personal information',
    apiEndpoint: '/children',
    hasChildFilter: false,
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
      { name: 'gender', label: 'Gender', type: 'select', required: false, options: ['Male', 'Female', 'Other'] },
      { name: 'blood_type', label: 'Blood Type', type: 'select', required: false, options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] },
      { name: 'allergies', label: 'Allergies', type: 'textarea', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['name', 'date_of_birth', 'gender', 'blood_type'],
    aiPromptTemplate: 'Analyze this child\'s profile and provide age-appropriate parenting insights',
  },
  {
    key: 'milestones',
    path: '/milestones',
    title: 'Development Milestones',
    icon: '🏆',
    description: 'Track developmental milestones and achievements',
    apiEndpoint: '/milestones',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Physical', 'Cognitive', 'Social', 'Language', 'Emotional', 'Self-Care'] },
      { name: 'achieved_date', label: 'Achieved Date', type: 'date', required: false },
      { name: 'expected_age_months', label: 'Expected Age (months)', type: 'number', required: false },
      { name: 'status', label: 'Status', type: 'select', required: true, options: ['Not Started', 'In Progress', 'Achieved', 'Delayed'] },
    ],
    listColumns: ['title', 'category', 'status', 'achieved_date'],
    aiPromptTemplate: 'Analyze this child\'s developmental milestones and provide insights on their progress',
  },
  {
    key: 'activities',
    path: '/activities',
    title: 'Activity Planning',
    icon: '🎨',
    description: 'Plan and track activities for your children',
    apiEndpoint: '/activities',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Educational', 'Physical', 'Creative', 'Social', 'Outdoor', 'Indoor', 'Music', 'Reading'] },
      { name: 'scheduled_date', label: 'Scheduled Date', type: 'date', required: false },
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number', required: false },
      { name: 'status', label: 'Status', type: 'select', required: true, options: ['Planned', 'In Progress', 'Completed', 'Cancelled'] },
      { name: 'location', label: 'Location', type: 'text', required: false },
    ],
    listColumns: ['title', 'category', 'scheduled_date', 'status'],
    aiPromptTemplate: 'Suggest age-appropriate activities based on this child\'s activity history and interests',
  },
  {
    key: 'health_records',
    path: '/health_records',
    title: 'Health Records',
    icon: '🏥',
    description: 'Maintain comprehensive health records',
    apiEndpoint: '/health-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'record_type', label: 'Record Type', type: 'select', required: true, options: ['Checkup', 'Illness', 'Injury', 'Allergy', 'Surgery', 'Lab Result', 'Other'] },
      { name: 'record_date', label: 'Record Date', type: 'date', required: true },
      { name: 'provider', label: 'Provider', type: 'text', required: false },
      { name: 'severity', label: 'Severity', type: 'select', required: false, options: ['Low', 'Medium', 'High', 'Critical'] },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['title', 'record_type', 'record_date', 'severity'],
    aiPromptTemplate: 'Review this child\'s health records and provide health insights and recommendations',
  },
  {
    key: 'sleep_records',
    path: '/sleep_records',
    title: 'Sleep Tracking',
    icon: '😴',
    description: 'Monitor and improve sleep patterns',
    apiEndpoint: '/sleep-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'sleep_start', label: 'Sleep Start', type: 'time', required: true },
      { name: 'sleep_end', label: 'Sleep End', type: 'time', required: true },
      { name: 'quality', label: 'Quality', type: 'select', required: false, options: ['Excellent', 'Good', 'Fair', 'Poor'] },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['date', 'sleep_start', 'sleep_end', 'quality'],
    aiPromptTemplate: 'Analyze this child\'s sleep patterns and provide recommendations for better sleep',
  },
  {
    key: 'feeding_records',
    path: '/feeding_records',
    title: 'Feeding & Nutrition',
    icon: '🍼',
    description: 'Track meals, nutrition, and feeding schedules',
    apiEndpoint: '/feeding-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'meal_type', label: 'Meal Type', type: 'select', required: true, options: ['Breakfast', 'Lunch', 'Dinner', 'Snack', 'Bottle', 'Breastfeed'] },
      { name: 'food_items', label: 'Food Items', type: 'textarea', required: true },
      { name: 'quantity', label: 'Quantity', type: 'text', required: false },
      { name: 'meal_time', label: 'Meal Time', type: 'time', required: false },
      { name: 'calories', label: 'Calories', type: 'number', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['meal_type', 'food_items', 'meal_time', 'calories'],
    aiPromptTemplate: 'Analyze this child\'s nutrition and feeding patterns and suggest dietary improvements',
  },
  {
    key: 'growth_records',
    path: '/growth_records',
    title: 'Growth Tracking',
    icon: '📏',
    description: 'Track height, weight, and growth metrics',
    apiEndpoint: '/growth-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'measured_date', label: 'Measured Date', type: 'date', required: true },
      { name: 'height_cm', label: 'Height (cm)', type: 'number', required: false },
      { name: 'weight_kg', label: 'Weight (kg)', type: 'number', required: false },
      { name: 'head_circumference_cm', label: 'Head Circumference (cm)', type: 'number', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['measured_date', 'height_cm', 'weight_kg', 'head_circumference_cm'],
    aiPromptTemplate: 'Analyze this child\'s growth data and provide insights on their physical development',
  },
  {
    key: 'vaccinations',
    path: '/vaccinations',
    title: 'Vaccination Records',
    icon: '💉',
    description: 'Track vaccinations and immunization schedules',
    apiEndpoint: '/vaccinations',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'vaccine_name', label: 'Vaccine Name', type: 'text', required: true },
      { name: 'dose_number', label: 'Dose Number', type: 'number', required: false },
      { name: 'administered_date', label: 'Administered Date', type: 'date', required: true },
      { name: 'next_due_date', label: 'Next Due Date', type: 'date', required: false },
      { name: 'provider', label: 'Provider', type: 'text', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['vaccine_name', 'dose_number', 'administered_date', 'next_due_date'],
    aiPromptTemplate: 'Review this child\'s vaccination records and advise on upcoming immunizations',
  },
  {
    key: 'behavioral_notes',
    path: '/behavioral_notes',
    title: 'Behavioral Notes',
    icon: '🧠',
    description: 'Document and understand behavioral patterns',
    apiEndpoint: '/behavioral-notes',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'behavior', label: 'Behavior', type: 'textarea', required: true },
      { name: 'context', label: 'Context', type: 'textarea', required: false },
      { name: 'observed_date', label: 'Observed Date', type: 'date', required: true },
      { name: 'mood', label: 'Mood', type: 'select', required: false, options: ['Happy', 'Sad', 'Angry', 'Anxious', 'Calm', 'Excited', 'Frustrated', 'Tired'] },
      { name: 'severity', label: 'Severity', type: 'select', required: false, options: ['Low', 'Medium', 'High'] },
    ],
    listColumns: ['title', 'observed_date', 'mood', 'severity'],
    aiPromptTemplate: 'Analyze this child\'s behavioral patterns and provide guidance for parents',
  },
  {
    key: 'journal_entries',
    path: '/journal_entries',
    title: 'Daily Journal',
    icon: '📔',
    description: 'Keep a daily journal of memorable moments',
    apiEndpoint: '/journal-entries',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'mood', label: 'Mood', type: 'select', required: false, options: ['Happy', 'Peaceful', 'Exciting', 'Challenging', 'Proud', 'Emotional', 'Funny'] },
      { name: 'entry_date', label: 'Entry Date', type: 'date', required: true },
      { name: 'tags', label: 'Tags', type: 'text', required: false },
    ],
    listColumns: ['title', 'entry_date', 'mood', 'tags'],
    aiPromptTemplate: 'Based on these journal entries, provide insights on the child\'s experiences and development',
  },
  {
    key: 'medications',
    path: '/medications',
    title: 'Medication Tracker',
    icon: '💊',
    description: 'Track medications, dosages, and schedules',
    apiEndpoint: '/medications',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'name', label: 'Medication Name', type: 'text', required: true },
      { name: 'dosage', label: 'Dosage', type: 'text', required: true },
      { name: 'frequency', label: 'Frequency', type: 'select', required: true, options: ['Once Daily', 'Twice Daily', 'Three Times Daily', 'Four Times Daily', 'As Needed', 'Weekly', 'Monthly'] },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date', required: false },
      { name: 'prescribed_by', label: 'Prescribed By', type: 'text', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['name', 'dosage', 'frequency', 'start_date'],
    aiPromptTemplate: 'Review this child\'s medication schedule and provide safety insights',
  },
  {
    key: 'appointments',
    path: '/appointments',
    title: 'Appointments',
    icon: '📅',
    description: 'Schedule and manage appointments',
    apiEndpoint: '/appointments',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'provider', label: 'Provider', type: 'text', required: false },
      { name: 'location', label: 'Location', type: 'text', required: false },
      { name: 'appointment_date', label: 'Appointment Date', type: 'date', required: true },
      { name: 'appointment_type', label: 'Type', type: 'select', required: true, options: ['Checkup', 'Dental', 'Vision', 'Specialist', 'Vaccination', 'Emergency', 'Therapy', 'Other'] },
      { name: 'status', label: 'Status', type: 'select', required: true, options: ['Scheduled', 'Completed', 'Cancelled', 'Rescheduled', 'No Show'] },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['title', 'appointment_date', 'appointment_type', 'status'],
    aiPromptTemplate: 'Review this child\'s appointments and suggest any follow-ups or preventive care',
  },
  {
    key: 'emergency_contacts',
    path: '/emergency_contacts',
    title: 'Emergency Contacts',
    icon: '🚨',
    description: 'Manage emergency contact information',
    apiEndpoint: '/emergency-contacts',
    hasChildFilter: false,
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'relationship', label: 'Relationship', type: 'select', required: true, options: ['Parent', 'Grandparent', 'Sibling', 'Uncle/Aunt', 'Neighbor', 'Babysitter', 'Doctor', 'Other'] },
      { name: 'phone', label: 'Phone', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: false },
      { name: 'address', label: 'Address', type: 'textarea', required: false },
      { name: 'is_primary', label: 'Primary Contact', type: 'boolean', required: false },
    ],
    listColumns: ['name', 'relationship', 'phone', 'is_primary'],
    aiPromptTemplate: 'Review emergency contacts and suggest any improvements for emergency preparedness',
  },
  {
    key: 'learning_resources',
    path: '/learning_resources',
    title: 'Learning Resources',
    icon: '📚',
    description: 'Curate educational resources and materials',
    apiEndpoint: '/learning-resources',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'resource_type', label: 'Resource Type', type: 'select', required: true, options: ['Book', 'Video', 'App', 'Game', 'Website', 'Toy', 'Course', 'Other'] },
      { name: 'url', label: 'URL', type: 'text', required: false },
      { name: 'age_range_start', label: 'Age Range Start (months)', type: 'number', required: false },
      { name: 'age_range_end', label: 'Age Range End (months)', type: 'number', required: false },
      { name: 'category', label: 'Category', type: 'select', required: false, options: ['Language', 'Math', 'Science', 'Art', 'Music', 'Physical', 'Social Skills', 'Life Skills'] },
    ],
    listColumns: ['title', 'resource_type', 'category', 'age_range_start'],
    aiPromptTemplate: 'Suggest age-appropriate learning resources based on this child\'s interests and development',
  },
  {
    key: 'diaper_records',
    path: '/diaper_records',
    title: 'Diaper Tracker',
    icon: '🧷',
    description: 'Track diaper changes and potty training progress',
    apiEndpoint: '/diaper-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'change_time', label: 'Change Time', type: 'time', required: true },
      { name: 'type', label: 'Type', type: 'select', required: true, options: ['Wet', 'Dirty', 'Both', 'Dry'] },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['change_time', 'type', 'notes'],
    aiPromptTemplate: 'Analyze diaper change patterns',
  },
  {
    key: 'expenses',
    path: '/expenses',
    title: 'Expense Tracker',
    icon: '💰',
    description: 'Track childcare-related expenses and budgets',
    apiEndpoint: '/expenses',
    hasChildFilter: false,
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'amount', label: 'Amount ($)', type: 'number', required: true },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Childcare', 'Medical', 'Education', 'Clothing', 'Food', 'Toys', 'Activities', 'Equipment', 'Other'] },
      { name: 'expense_date', label: 'Date', type: 'date', required: true },
      { name: 'payment_method', label: 'Payment Method', type: 'select', required: false, options: ['Cash', 'Credit Card', 'Debit Card', 'Insurance', 'Other'] },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['title', 'amount', 'category', 'expense_date'],
    aiPromptTemplate: 'Analyze childcare expenses',
  },
  {
    key: 'caregiver_logs',
    path: '/caregiver_logs',
    title: 'Caregiver Log',
    icon: '👩‍👧',
    description: 'Track babysitter and caregiver sessions',
    apiEndpoint: '/caregiver-logs',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'caregiver_name', label: 'Caregiver Name', type: 'text', required: true },
      { name: 'relationship', label: 'Relationship', type: 'select', required: false, options: ['Babysitter', 'Grandparent', 'Nanny', 'Daycare', 'Family Friend', 'Au Pair', 'Other'] },
      { name: 'start_time', label: 'Start Time', type: 'time', required: true },
      { name: 'end_time', label: 'End Time', type: 'time', required: false },
      { name: 'activities', label: 'Activities', type: 'textarea', required: false },
      { name: 'rating', label: 'Rating (1-5)', type: 'number', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['caregiver_name', 'relationship', 'start_time', 'end_time'],
    aiPromptTemplate: 'Review caregiver sessions',
  },
  {
    key: 'daily_routines',
    path: '/daily_routines',
    title: 'Daily Routines',
    icon: '⏰',
    description: 'Build and manage daily schedules and routines',
    apiEndpoint: '/daily-routines',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Routine Name', type: 'text', required: true },
      { name: 'time_of_day', label: 'Time of Day', type: 'select', required: true, options: ['Morning', 'Midday', 'Afternoon', 'Evening', 'Night'] },
      { name: 'scheduled_time', label: 'Scheduled Time', type: 'time', required: false },
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number', required: false },
      { name: 'category', label: 'Category', type: 'select', required: false, options: ['Hygiene', 'Meal', 'Nap', 'Play', 'Learning', 'Exercise', 'Chore', 'Other'] },
      { name: 'days_of_week', label: 'Days (e.g. Mon,Tue,Wed)', type: 'text', required: false },
      { name: 'is_active', label: 'Active', type: 'boolean', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['title', 'time_of_day', 'scheduled_time', 'category'],
    aiPromptTemplate: 'Optimize daily routine schedule',
  },
  {
    key: 'tooth_records',
    path: '/tooth_records',
    title: 'Tooth Tracker',
    icon: '🦷',
    description: 'Track baby teeth eruption and loss',
    apiEndpoint: '/tooth-records',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'tooth_name', label: 'Tooth Name', type: 'select', required: true, options: ['Upper Right Central Incisor', 'Upper Left Central Incisor', 'Upper Right Lateral Incisor', 'Upper Left Lateral Incisor', 'Upper Right Canine', 'Upper Left Canine', 'Upper Right First Molar', 'Upper Left First Molar', 'Upper Right Second Molar', 'Upper Left Second Molar', 'Lower Right Central Incisor', 'Lower Left Central Incisor', 'Lower Right Lateral Incisor', 'Lower Left Lateral Incisor', 'Lower Right Canine', 'Lower Left Canine', 'Lower Right First Molar', 'Lower Left First Molar', 'Lower Right Second Molar', 'Lower Left Second Molar'] },
      { name: 'tooth_position', label: 'Position', type: 'select', required: false, options: ['Upper Right', 'Upper Left', 'Lower Right', 'Lower Left'] },
      { name: 'event_type', label: 'Event', type: 'select', required: true, options: ['Erupted', 'Lost', 'Cavity', 'Treatment'] },
      { name: 'event_date', label: 'Date', type: 'date', required: true },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['tooth_name', 'event_type', 'event_date'],
    aiPromptTemplate: 'Review dental development progress',
  },
  {
    key: 'photo_memories',
    path: '/photo_memories',
    title: 'Memory Book',
    icon: '📸',
    description: 'Document special moments and memories',
    apiEndpoint: '/photo-memories',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'memory_date', label: 'Date', type: 'date', required: true },
      { name: 'category', label: 'Category', type: 'select', required: false, options: ['First Time', 'Birthday', 'Holiday', 'Family', 'Achievement', 'Funny Moment', 'Outing', 'Everyday', 'Other'] },
      { name: 'location', label: 'Location', type: 'text', required: false },
      { name: 'people_in_photo', label: 'People Present', type: 'text', required: false },
    ],
    listColumns: ['title', 'memory_date', 'category', 'location'],
    aiPromptTemplate: 'Create a memory narrative from these entries',
  },
  {
    key: 'chores',
    path: '/chores',
    title: 'Chore Chart',
    icon: '✅',
    description: 'Assign and track age-appropriate chores',
    apiEndpoint: '/chores',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'title', label: 'Chore', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: false },
      { name: 'frequency', label: 'Frequency', type: 'select', required: true, options: ['Daily', 'Weekly', 'Bi-Weekly', 'Monthly', 'One-Time'] },
      { name: 'assigned_date', label: 'Assigned Date', type: 'date', required: false },
      { name: 'due_date', label: 'Due Date', type: 'date', required: false },
      { name: 'status', label: 'Status', type: 'select', required: true, options: ['Pending', 'In Progress', 'Completed', 'Skipped'] },
      { name: 'reward', label: 'Reward', type: 'text', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['title', 'frequency', 'status', 'due_date'],
    aiPromptTemplate: 'Suggest age-appropriate chores',
  },
  {
    key: 'allergy_logs',
    path: '/allergy_logs',
    title: 'Allergy Log',
    icon: '⚠️',
    description: 'Track allergies, reactions, and treatments',
    apiEndpoint: '/allergy-logs',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'allergen', label: 'Allergen', type: 'text', required: true },
      { name: 'severity', label: 'Severity', type: 'select', required: true, options: ['Mild', 'Moderate', 'Severe', 'Life-Threatening'] },
      { name: 'reaction', label: 'Reaction', type: 'textarea', required: false },
      { name: 'first_observed', label: 'First Observed', type: 'date', required: false },
      { name: 'last_reaction', label: 'Last Reaction', type: 'date', required: false },
      { name: 'treatment', label: 'Treatment', type: 'textarea', required: false },
      { name: 'is_confirmed', label: 'Confirmed by Doctor', type: 'boolean', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['allergen', 'severity', 'first_observed', 'is_confirmed'],
    aiPromptTemplate: 'Review allergy profile and suggest precautions',
  },
  {
    key: 'playdates',
    path: '/playdates',
    title: 'Playdates',
    icon: '🤝',
    description: 'Schedule and track playdates with friends',
    apiEndpoint: '/playdates',
    hasChildFilter: true,
    fields: [
      { name: 'child_id', label: 'Child', type: 'child_select', required: true },
      { name: 'friend_name', label: 'Friend Name', type: 'text', required: true },
      { name: 'friend_age', label: 'Friend Age', type: 'text', required: false },
      { name: 'playdate_date', label: 'Date', type: 'date', required: true },
      { name: 'start_time', label: 'Start Time', type: 'time', required: false },
      { name: 'end_time', label: 'End Time', type: 'time', required: false },
      { name: 'location', label: 'Location', type: 'text', required: false },
      { name: 'activity', label: 'Activity', type: 'textarea', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['friend_name', 'playdate_date', 'location', 'activity'],
    aiPromptTemplate: 'Suggest playdate activities based on interests',
  },
  {
    key: 'shopping_lists',
    path: '/shopping_lists',
    title: 'Shopping List',
    icon: '🛒',
    description: 'Manage shopping lists for childcare items',
    apiEndpoint: '/shopping-lists',
    hasChildFilter: false,
    fields: [
      { name: 'item_name', label: 'Item Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Diapers & Wipes', 'Formula & Food', 'Clothing', 'Toys', 'Books', 'Health & Safety', 'Furniture', 'School Supplies', 'Other'] },
      { name: 'quantity', label: 'Quantity', type: 'text', required: false },
      { name: 'priority', label: 'Priority', type: 'select', required: false, options: ['Low', 'Medium', 'High', 'Urgent'] },
      { name: 'is_purchased', label: 'Purchased', type: 'boolean', required: false },
      { name: 'estimated_cost', label: 'Estimated Cost ($)', type: 'number', required: false },
      { name: 'store', label: 'Store', type: 'text', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', required: false },
    ],
    listColumns: ['item_name', 'category', 'priority', 'is_purchased'],
    aiPromptTemplate: 'Suggest essential items for the shopping list',
  },
  {
    key: 'ai_advisor',
    path: '/ai-advisor',
    title: 'AI Parenting Advisor',
    icon: '🤖',
    description: 'Get personalized AI-powered parenting advice',
    apiEndpoint: null,
    hasChildFilter: false,
    fields: [],
    listColumns: [],
    aiPromptTemplate: '',
    isSpecial: true,
  },
];

export default features;

export function getFeatureByKey(key) {
  return features.find((f) => f.key === key);
}

export function getFeatureByPath(path) {
  return features.find((f) => f.path === path || f.path === `/${path}`);
}

export function getCRUDFeatures() {
  return features.filter((f) => !f.isSpecial);
}
