'use strict';

/**
 * Single source of truth for the CRUD feature tables.
 *
 * Both /api/reports and /api/search read this list so a table can never be
 * counted by one endpoint and forgotten by the other. `path` matches the
 * `path` value in frontend/src/config/features.js, `scope` says how rows are
 * tied to the authenticated account, and `search`/`title`/`subtitle` describe
 * which text columns are meaningful to a person searching.
 */
const FEATURE_TABLES = [
  {
    table: 'children',
    feature: 'children',
    path: '/children',
    scope: 'user',
    search: ['name', 'notes'],
    title: ['name'],
    subtitle: ['date_of_birth', 'gender'],
  },
  {
    table: 'milestones',
    feature: 'milestones',
    path: '/milestones',
    scope: 'child',
    search: ['title', 'description', 'category'],
    title: ['title'],
    subtitle: ['category', 'status', 'achieved_date'],
  },
  {
    table: 'activities',
    feature: 'activities',
    path: '/activities',
    scope: 'child',
    search: ['title', 'description', 'category', 'location'],
    title: ['title'],
    subtitle: ['category', 'status', 'scheduled_date'],
  },
  {
    table: 'health_records',
    feature: 'health_records',
    path: '/health_records',
    scope: 'child',
    search: ['title', 'description', 'provider', 'notes'],
    title: ['title'],
    subtitle: ['record_type', 'record_date'],
  },
  {
    table: 'sleep_records',
    feature: 'sleep_records',
    path: '/sleep_records',
    scope: 'child',
    search: ['quality', 'notes'],
    title: ['quality'],
    subtitle: ['date'],
  },
  {
    table: 'feeding_records',
    feature: 'feeding_records',
    path: '/feeding_records',
    scope: 'child',
    search: ['meal_type', 'food_items', 'notes'],
    title: ['meal_type'],
    subtitle: ['food_items', 'meal_time'],
  },
  {
    table: 'growth_records',
    feature: 'growth_records',
    path: '/growth_records',
    scope: 'child',
    search: ['notes'],
    title: ['measured_date'],
    subtitle: ['height_cm', 'weight_kg'],
  },
  {
    table: 'vaccinations',
    feature: 'vaccinations',
    path: '/vaccinations',
    scope: 'child',
    search: ['vaccine_name', 'provider', 'notes'],
    title: ['vaccine_name'],
    subtitle: ['administered_date', 'provider'],
  },
  {
    table: 'behavioral_notes',
    feature: 'behavioral_notes',
    path: '/behavioral_notes',
    scope: 'child',
    search: ['title', 'behavior', 'context'],
    title: ['title'],
    subtitle: ['observed_date', 'mood'],
  },
  {
    table: 'journal_entries',
    feature: 'journal_entries',
    path: '/journal_entries',
    scope: 'child',
    search: ['title', 'content', 'tags'],
    title: ['title'],
    subtitle: ['entry_date', 'mood'],
  },
  {
    table: 'medications',
    feature: 'medications',
    path: '/medications',
    scope: 'child',
    search: ['name', 'dosage', 'prescribed_by', 'notes'],
    title: ['name'],
    subtitle: ['dosage', 'frequency'],
  },
  {
    table: 'appointments',
    feature: 'appointments',
    path: '/appointments',
    scope: 'child',
    search: ['title', 'provider', 'location', 'notes'],
    title: ['title'],
    subtitle: ['appointment_date', 'status'],
  },
  {
    table: 'emergency_contacts',
    feature: 'emergency_contacts',
    path: '/emergency_contacts',
    scope: 'user',
    search: ['name', 'relationship', 'phone', 'email'],
    title: ['name'],
    subtitle: ['relationship', 'phone'],
  },
  {
    table: 'learning_resources',
    feature: 'learning_resources',
    path: '/learning_resources',
    scope: 'child',
    search: ['title', 'description', 'category', 'resource_type'],
    title: ['title'],
    subtitle: ['resource_type', 'category'],
  },
  {
    table: 'diaper_records',
    feature: 'diaper_records',
    path: '/diaper_records',
    scope: 'child',
    search: ['type', 'notes'],
    title: ['type'],
    subtitle: ['change_time', 'notes'],
  },
  {
    table: 'expenses',
    feature: 'expenses',
    path: '/expenses',
    scope: 'user',
    search: ['title', 'category', 'notes'],
    title: ['title'],
    subtitle: ['category', 'expense_date'],
  },
  {
    table: 'caregiver_logs',
    feature: 'caregiver_logs',
    path: '/caregiver_logs',
    scope: 'user',
    search: ['caregiver_name', 'activities', 'notes'],
    title: ['caregiver_name'],
    subtitle: ['relationship', 'start_time'],
  },
  {
    table: 'daily_routines',
    feature: 'daily_routines',
    path: '/daily_routines',
    scope: 'child',
    search: ['title', 'category', 'notes'],
    title: ['title'],
    subtitle: ['time_of_day', 'scheduled_time'],
  },
  {
    table: 'tooth_records',
    feature: 'tooth_records',
    path: '/tooth_records',
    scope: 'child',
    search: ['tooth_name', 'notes'],
    title: ['tooth_name'],
    subtitle: ['event_type', 'event_date'],
  },
  {
    table: 'photo_memories',
    feature: 'photo_memories',
    path: '/photo_memories',
    scope: 'child',
    search: ['title', 'description', 'location', 'people_in_photo'],
    title: ['title'],
    subtitle: ['memory_date', 'category'],
  },
  {
    table: 'chores',
    feature: 'chores',
    path: '/chores',
    scope: 'child',
    search: ['title', 'description', 'notes'],
    title: ['title'],
    subtitle: ['frequency', 'status'],
  },
  {
    table: 'allergy_logs',
    feature: 'allergy_logs',
    path: '/allergy_logs',
    scope: 'child',
    search: ['allergen', 'reaction', 'treatment', 'notes'],
    title: ['allergen'],
    subtitle: ['severity', 'is_confirmed'],
  },
  {
    table: 'playdates',
    feature: 'playdates',
    path: '/playdates',
    scope: 'child',
    search: ['friend_name', 'location', 'activity', 'notes'],
    title: ['friend_name'],
    subtitle: ['playdate_date', 'location'],
  },
  {
    table: 'shopping_lists',
    feature: 'shopping_lists',
    path: '/shopping_lists',
    scope: 'user',
    search: ['item_name', 'category', 'store', 'notes'],
    title: ['item_name'],
    subtitle: ['category', 'priority'],
  },
];

module.exports = { FEATURE_TABLES };
